[[main]]
  identifier = "article"
  name = "文章"
  url = "article"
  weight = 1

[[main]]
  identifier = "about"
  name = "笔记"
  url = "about"
  weight = 1

[[main]]
  name = "智力题"
  url = "intelligence"
 weight = 7

[[main]]
  name = "解题"
  url = "problems"
 weight = 8

[[main]]
  identifier = "算法"
  name = "算法"
  url = "interview"
  weight = 9

[[main]]
  parent = "算法"
  name = "剑指offer"
  url = "interview/algorithm"

[[main]]
  parent = "算法"
  name = "算法实战"
  url = "interview/algorithm_interview"

[[main]]
  parent = "算法"
  name = "优质题目"
  url = "interview/quality_questions"

[[main]]
  identifier = "数据结构与排序算法"
  name = "必知必会"
  url = "data_structure_and_sort"
  weight = 10

[[main]]
  parent = "数据结构与排序算法"
  name = "数据结构"
  url = "data_structure_and_sort/datastructure"

[[main]]
  parent = "数据结构与排序算法"
  name = "排序算法"
  url = "data_structure_and_sort/sort"

[[main]]
  name = "小知识"
  url = "tips"
 weight = 12


[[main]]
  identifier = "archive"
  name = "更新日志"
  url = "archive"
  weight = 13