apiVersion: v1
kind: Pod
metadata:
  name: nginx-low
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "100Mi"
          cpu: "1300m"
  priorityClassName: low-priority
