apiVersion: v1
kind: Pod
metadata:
  name: podaffinity
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: name
                operator: In # 匹配规则为 key必须要在pod1或pod2中
                values:
                  - "pod1"
                  - "pod2"
          topologyKey: "topologyX"
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: name
                  operator: In
                  values:
                    - "pod1"
                    - "pod2"
            topologyKey: "topologyY"
 
