apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod
      image: nginx
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "touch /mnt/SUCCESS && exit 0 || exit 1" #创建一个SUCCESS文件后退出
      volumeMounts:
        - name: pv-pvc-test
          mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: pv-pvc-test
      persistentVolumeClaim:
      claimName: pvc-test #与PVC名称保持一致
